---
title: "Descriptive analysis"
author: "Jae Yeon Kim"
output:
html_document:
  toc: True
  theme: united
  number_sections: True
---

## Setup

```{r}

# Clean up the environment

# rm(list = ls())

# if (!require("pacman")) install.packages("pacman")
pacman::p_load(
        tidyverse, # for the tidyverse framework
        data.table, # for fast data wrangling 
        patchwork, # for arranging ggplots
        here, # for reproducibility
        rvest, # for parsing html

        ### ggplot themes
        ggsci, # for pub-ready ggplots 
        ggpubr, # for arranging ggplots
        ggthemes, # for fancy ggplot themes
        ggrepel, # for annotations 
        
        ### Spatial analysis
        tidygeocoder, # for geocoding
        USAboundaries, # for shape files 
        ggspatial, # for spatial data framework 
        maps, # maps 
#       ggmap, # for static maps
        tmap,
        tmaptools, 
        spData,
        sf, 
#       leaflet, # for interactive maps

        ### Time series analysis
        ggseas, # for seasonality adjustment
        fpp2, # for detecting seasonality in data

        ### Interactiev maps
        gganimate, # for animated maps
        gifski # for animated maps
)

# devtools::install_github("jaeyk/makereproducible")
library(makereproducible)

# Import R scripts
source(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/functions/misc.r"))

script_list <- list(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/functions/misc.r"),
     here("functions", "data_viz.r"))

for (i in 1:length(script_list))
    {source(script_list[[i]])}

# for publication-friendly theme
theme_set(theme_pubr())
```

## Load files

N of Asian orgs: 299
N of Latino orgs: 519

```{r include=FALSE}

# Load files

asian_org <- read_csv(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/raw_data/asian_orgs.csv"))

latino_org <- read_csv(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/raw_data/latino_orgs.csv"))

reagan <- read_csv(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/raw_data/reagan_budget.csv"))

# Chinese service org

chinese_service_org <- read_csv(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/raw_data/chinese_service_org.csv"))

# Mexican service org

mexican_service_org <- read_csv(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/raw_data/mexican_service_org.csv"))

```

## Descriptive analysis

### Cross-sectional analysis

- [] Turn this into stacked bar plot. 

```{r}

aa_org_n <- asian_org %>%
    dplyr::select(City, Type) %>%
    group_by(Type) %>%
    summarize(n = n()) %>%
    arrange(desc(n)) %>%
    ggplot(aes(x = reorder(Type, -n), y = n)) +
        geom_col() +
        theme_base() +
        labs(x = "Type", y = "Count",
             title = "Asian organizations (N = 299)",
             subtitle = "Sorted by organization types")

latino_org_n <- latino_org %>%
    dplyr::select(City, Type) %>%
    group_by(Type) %>%
    summarize(n = n()) %>%
    arrange(desc(n)) %>%
    ggplot(aes(x = reorder(Type, -n), y = n)) +
        geom_col() +
        theme_base() +
        labs(x = "Type", y = "Count",
             title = "Latino organizations (N = 519)",
             subtitle = "Sorted by organization types")

aa_org_n + latino_org_n

ggsave(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/outputs/asian_latino_orgs_n.png"), width = 10)

```
### Time-series analysis

#### Turning into time-series data

```{r}

# Fill 0 years to each subset
asian_cbo_year <- org_to_ts(asian_org %>% filter(Type == "CBO"))
asian_advo_year <- org_to_ts(asian_org %>% filter(Type == "Advocacy"))
asian_hybrid_year <- org_to_ts(asian_org %>% filter(Type == "Hybrid"))

latino_cbo_year <- org_to_ts(latino_org %>% filter(Type == "CBO"))
latino_advo_year <- org_to_ts(latino_org %>% filter(Type == "Advocacy"))
latino_hybrid_year <- org_to_ts(latino_org %>% filter(Type == "Hybrid"))

# Bind them
asian_year <- bind_rows(asian_cbo_year, asian_advo_year, asian_hybrid_year)
latino_year <- bind_rows(latino_cbo_year, latino_advo_year, latino_hybrid_year)

write_csv(asian_year, make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/processed_data/asian_year.csv"))

write_csv(latino_year, make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/processed_data/latino_year.csv"))

```

#### Plotting

```{r}

# Merge

merged <- bind_rows(mutate(asian_year, group = "Asian Americans"),
          mutate(latino_year, group = "Latinos"))

# Plot

freq_sum <- merged %>%
    group_by(F.year, group, Type) %>%
    summarize(freq_sum = sum(Freq))

write_csv(freq_sum, make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/processed_data/freq_sum.csv"))

freq_sum %>%
    ggplot(aes(x = F.year, y = freq_sum)) +
        geom_point() +
        geom_line() +
        stat_stl(frequency = 4, s.window = "periodic", col = "blue", size = 1) +
        labs(title = " Grey: Raw trend \n Blue: Seaonality adjusted trend",
             x = "Year",
             y = "Number of organizations founded in each year") +
        facet_grid(Type~group) +
        xlim(c(1960,2017)) +
        geom_vline(xintercept = c(1980), linetype = "dashed", col = "red") +
        annotate(geom="text", x = 1972, y = 13, label="War on Poverty",
                  color="red") +
        annotate(geom="text", x = 1990, y = 13, label="Post-Reagan period",
                  color="red") +
        scale_y_continuous(breaks = scales::pretty_breaks()) # integers

ggsave(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/outputs/org_founding_year.png"), height = 7, width = 12)

```

```{r}

panethnic <- freq_sum %>%
    filter(Type == "CBO") %>%
    ggplot(aes(x = F.year, y = freq_sum)) +
        geom_point() +
        geom_line() +
        labs(x = "Year", y = "Number of organizations founded in each year",
             title = "Panethnic organizations",
             subtitle = "Only included CBOs") +
        facet_grid(~group) +
        xlim(c(1960,2017))  +
        geom_vline(xintercept = c(1980), linetype = "dashed", col = "red") +
        annotate(geom="text", x = 1972, y = 13, label="War on Poverty",
                  color="red") +
        annotate(geom="text", x = 1990, y = 13, label="Post-Reagan period",
                  color="red") +
        scale_y_continuous(breaks = scales::pretty_breaks()) +
        ylim(c(0,20))

ethnic <- bind_rows(mutate(chinese_service_org[,c("Name", "F.year")], group = "Chinese"),
          mutate(mexican_service_org[,c("Name", "F.year")], group = "Mexicans")) %>%
    count(F.year, group) %>%
    ggplot(aes(x = F.year, y = n)) +
        geom_point() +
        geom_line() +
        labs(x = "Year", y = "Number of organizations founded in each year",
             title = "Ethnic organizations",
             subtitle = "Only included CBOs") +
        facet_grid(~group) +
        xlim(c(1960,2017))  +
        geom_vline(xintercept = c(1980), linetype = "dashed", col = "red") +
        annotate(geom="text", x = 1972, y = 13, label="War on Poverty",
                  color="red") +
        annotate(geom="text", x = 1990, y = 13, label="Post-Reagan period",
                  color="red") +
        scale_y_continuous(breaks = scales::pretty_breaks()) +
        ylim(c(0,20))

panethnic / ethnic

ggsave(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/outputs/org_founding_year_combined.png"), height = 12, width = 13)
```

## Geospatial analysis

### Prep data 

```{r}

# register_google(key = "google api key")

# Subset data
## Asian

asian_org_dt <- data.table(asian_org)

asian_address <- asian_org_dt[F.year <= 1981, .(Address, F.year, Name, Type, States, County, City), ] %>% as.data.frame()

## Latino
latino_org_dt <- data.table(latino_org)

latino_address <- latino_org_dt[F.year <= 1981, .(Address, F.year, Name, Type, States, County, City), ] %>% as.data.frame()

org_address <- merge_by_group(asian_address, latino_address)

# Export 
write_csv(org_address, here("processed_data", "org_address.csv"))

# EDA

org_address %>%
    count(States, sort = TRUE) 
# California = 79, DC = 11, NY = 11

org_address %>%
    count(States, category, sort = TRUE) 
# California - Asian = 43, California - Latino = 36

org_address %>%
    count(County, sort = TRUE)
# San Francisco 25, Los Angeles 19, Alameda 10, Sacramento 7

org_address %>%
    count(County, category, sort = TRUE)
# San Francisco - Asian = 20, Los Angeles - Asian = 10, Alameda - Asian = 5, Los Angeles - Latino = 9, Alameda - Asian 5, Alameda - Latino 5
```

### Import geocodes 

```{r}
# Fix the problematic addresses using Bing (done in Python)
lat_longs <- read_csv(here("processed_data", "org_lat_logs_fixed.csv"))[,-1]

glimpse(lat_longs)

```

### Making maps

#### State level 

```{r}

# Filter; Data ready 
df <- lat_longs %>%
    filter(!is.na(Address)) %>%
    filter(!str_detect(Address, "Honolu"))

# Prepare US map layout 

## Remove Hawaii and Alaska from the state name list
state_names <- state.name[!(state.name %in% c("Hawaii", "Alaska"))]

## Extract the boundaries 
historical_us <- us_counties("1981-12-31",
                             states = state_names,
                             resolution = "high")

# Data points 
sites <- sf::st_as_sf(df, 
                      coords = c("longtitude", 
                                 "latitude"),
                      crs = 4326, 
                      agr = "identity")

# Map
tmap::tm_shape(historical_us, projection = 2163) +
    tm_polygons() +
    tm_shape(sites) +
    tm_dots(size = 1)

```
#### County level 

#### City level 


```{r}

# Base map

us_states <- map_data("state")
us_county <- map_data("county")

# Get state names

asian_org$region <- tolower(abbr2state(asian_org$States))
latino_org$region <- tolower(abbr2state(latino_org$States))

# Create fuctions

## No year

county_map <- function(data){
  data_county<- count(data, County)

  colnames(data_county)[1] <- "subregion"

  data_county$subregion <- as.character(data_county$subregion)
  data_county$subregion <- tolower(data_county$subregion)

  us_county_data <- left_join(us_county, data_county)
  return(us_county_data)
}

state_map <- function(data){
  data_state<- count(data, region)

  colnames(data_state)[1] <- "region"

  data_state$region <- as.character(data_state$region)
  data_state$region <- tolower(data_state$region)

  us_state_data <- left_join(us_states, data_state)
  return(us_state_data)
}

county_year_map <- function(data){
  data_county<- count(data, County, F.year)

  colnames(data_county)[1] <- "subregion"

  data_county$subregion <- as.character(data_county$subregion)
  data_county$subregion <- tolower(data_county$subregion)

  us_county_data <- left_join(us_county, data_county)
  return(us_county_data)
}

state_year_map <- function(data){
  data_state<- count(data, region, F.year)

  colnames(data_state)[1] <- "region"

  data_state$region <- as.character(data_state$region)
  data_state$region <- tolower(data_state$region)

  us_state_data <- left_join(us_states, data_state)
  return(us_state_data)
}

# Get state and county maps

asian_state_map <- state_map(asian_org %>% filter(F.year <= 1980))
latino_state_map <- state_map(latino_org %>% filter(F.year <= 1980))

asian_county_map <- county_map(asian_org %>% filter(F.year <= 1980))
latino_county_map <- county_map(latino_org %>% filter(F.year <= 1980))

asian_county_year_map <- county_year_map(asian_org %>% filter(F.year <= 1980))
latino_county_year_map <- county_year_map(latino_org %>% filter(F.year <= 1980))

write_rds(asian_county_map, "/home/jae/analyzing-asian-american-latino-civic-infrastructure/processed_data/asian_county_map")
write_rds(latino_county_map, "/home/jae/analyzing-asian-american-latino-civic-infrastructure/processed_data/latino_county_map")

```

```{r}

# Asian Americans

## State

asian_state <- ggplot(data = asian_state_map,
            aes(x = long, y = lat,
                group = group, fill = n))+
  geom_polygon(color = "gray10", size = 0.05) +
  labs(fill = "Number of organizations",
       title = "Asian American community-based and advocacy organizations",
       subtitle = "In States (1980)")

## County

asian_county <- ggplot(data = asian_county_map,
            aes(x = long, y = lat,
                group = group, fill = n))+
  geom_polygon(color = "gray10", size = 0.05) +
  labs(fill = "Number of organizations",
       title = "Asian American community-based and advocacy organizations",
       subtitle = "In Counties (1980)") +
  ditch_the_axes

# Latinos

## State

latino_state <- ggplot(data = latino_state_map,
            aes(x = long, y = lat,
                group = group, fill = n))+
  geom_polygon(color = "gray10", size = 0.05) +
  labs(fill = "Number of organizations",
       subtitle = "In States (1980)",
       title = "Latino community-based and advocacy organizations") +
  ditch_the_axes

## County

latino_county <-
ggplot(data = latino_county_map,
            aes(x = long, y = lat,
                group = group, fill = n))+
  geom_polygon(color = "gray10", size = 0.05) +
  labs(fill = "Number of organizations",
       title = "Latino community-based advocacy organizations",
       subtitle = "In Counties (1980)") +
  ditch_the_axes

ggarrange(asian_county, latino_county, common.legend = TRUE, ncol = 1, nrow =2)

ggsave("/home/jae/analyzing-asian-american-latino-civic-infrastructure/outputs/county_maps.png", width = 10, height = 15)

ggarrange(asian_state, latino_state, common.legend = TRUE, ncol = 1, nrow =2)

ggsave("/home/jae/analyzing-asian-american-latino-civic-infrastructure/outputs/state_maps.png", width = 10, height = 15)

```
