---
title: "Additional robustness check"
author: "Jae Yeon Kim"
output:
html_document:
  toc: True
  theme: united
  number_sections: True
---

# Setup 

```{r}

# Import libraries 

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
        tidyverse, # for the tidyverse framework
        patchwork, # for arranging ggplots 
        ggpubr, # for arranging ggplots 
        ggthemes, # for fancy ggplot themes
        broom, # for modeling
        here, # for reproducibility 
        USAboundaries) # USA cities, counties, and states 
        
# devtools::install_github("jaeyk/makereproducible")
library(makereproducible)

# Import R scripts

script_list <- list.files(paste0(here::here(), "/functions"),
  pattern = "*.r|*.R",
  full.names = TRUE
)

for (i in 1:length(script_list))
{
  source(script_list[[i]])
}

# for publication-friendly theme
theme_set(theme_pubr())
```

# Load files

```{r}
# Load files

asian_org <- read_csv(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/raw_data/asian_orgs.csv"))

latino_org <- read_csv(make_here("/home/jae/analyzing-asian-american-latino-civic-infrastructure/raw_data/latino_orgs.csv"))

historical_asian_latino_pop <- read_csv(here("processed_data", "historical_asian_latino_pop.csv"))

cap_census <- read_csv(here("processed_data", "cap_census.csv"))

```
