---
title: "Additional robustness check"
author: "Jae Yeon Kim"
output:
html_document:
  toc: True
  theme: united
  number_sections: True
---

# Setup 

```{r, echo=FALSE}

# Import libraries 

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
        readstata13, # import stata 13 files 
        tidyverse, # the tidyverse framework
        patchwork, # arranging ggplots 
        ggpubr, # arranging ggplots 
        ggthemes, # fancy ggplot themes
        broom, # modeling
        here, # reproducibility 
        magrittr, # %<>%
        nlme, # GLS
        stargazer, # latex table 
        lmtest,
        sandwich)
  
# devtools::install_github("jaeyk/makereproducible")
library(makereproducible)

# Import R scripts

script_list <- list.files(paste0(here::here(), "/functions"),
  pattern = "*.r|*.R",
  full.names = TRUE
)

for (i in 1:length(script_list))
{
  source(script_list[[i]])
}

# for publication-friendly theme
theme_set(theme_pubr())

```

# Load files and wrangle data 

```{r}

wop_asian_city <- read_csv(here("raw_data", "asian_orgs.csv")) %>%
  filter(F.year <= 1981) %>%
  mutate(County = trimws(County)) %>%
  count(City, County, States, Type) 

wop_latino_city <- read_csv(here("raw_data", "latino_orgs.csv")) %>%
  filter(F.year <= 1981) %>%
  mutate(County = trimws(County)) %>%
  count(City, County, States, Type) 

oeo_census <- read.csv(here("processed_data" , "oeo_census.csv"))

historical_census_county <- read_csv(here("processed_data", "historical_census_county.csv")) %>%
  mutate(County = toupper(County)) %>%
  filter(County != "STATE TOTAL") %>%
  mutate(County = trimws(County)) 

historical_census_county <- add_state_abb(historical_census_county) %>%
  dplyr::select(State, County, year, poverty_rate, pop_size, State_abb) %>%
  filter(year == 1980)

```

# Merge data

- N of obs: 95 counties 

```{r}

df1 <- merge_by_group(wop_asian_city, wop_latino_city) # 67 counties 

df2 <- left_join(df1, oeo_census, by = c("County" , "States" , "City"))

df3 <- left_join(df2, historical_census_county, 
        by = c("County",
               "States" = "State_abb"))

```

# Model data 

```{r}

df3 <- df3 %<>%
  mutate(category = factor(category),
         Asian_per = as.numeric(Asian_per),
         Latino_per = as.numeric(Latino_per),
         OEO_per = round(df3$OEO_fund/sum(df3$OEO_fund, na.rm = TRUE),2)*100,
         pop_size = scales::rescale(pop_size, to = c(0,100)),
         log_n = log(n))

```

```{r}

df3 <- replace_na(df3, 
                  list(Asian_per = 0, 
                       Latino_per = 0, 
                       OEO_fund = 0, 
                       OEO_per = 0, 
                       pop_size = 0, 
                       poverty_rate = 0)
                  )

```

OLS AIC:407.94
Logged OLS AIC:161.444
Poisson AIC:329.749
Negative binomial AIC:331.296

```{r}
lm.out <- lm(n ~ OEO_per + poverty_rate + Asian_per + Latino_per + pop_size + Type + category, data = df3)

lm_log.out <- lm(log_n ~ OEO_per + poverty_rate + Asian_per + Latino_per + pop_size + Type + category, data = df3)

poisson.out <- glm(n ~ OEO_per + poverty_rate + Asian_per + Latino_per + pop_size + Type + category, data = df3, family = "poisson")

nb.out <- MASS::glm.nb(n ~ OEO_per + poverty_rate + Asian_per + Latino_per + pop_size + Type + category, data = df3)

```

```{r}
cat(paste0("OLS AIC:", round(AIC(lm.out), 3), "\n",   
           "Logged OLS AIC:", round(AIC(lm_log.out), 3), "\n",
           "Poisson AIC:", round(AIC(poisson.out), 3), "\n",
           "Negative binomial AIC:", round(AIC(nb.out), 3)))
      
```

```{r}

df3 <- df3 %>% filter(Type == "CSO")

m1 <- lm(log_n ~ OEO_per + category, data = df3)

m2 <- lm(log_n ~ OEO_per + category + Asian_per + Latino_per, data = df3)

m3 <- lm(log_n ~ OEO_per + category + Asian_per + Latino_per + poverty_rate, data = df3)

lm_white <- coeftest(m3, vcov = vcovHC(m3, type = "HC0"))

# LaTeX Output 
stargazer(m1, m2, m3, lm_white,
          title = "Cross-sectional regression analysis results",
          covariate.labels = c("OEO grants",
                                "Latino org",
                                "Asian pop",
                                "Latino pop",
                                "Poverty rate"),
          dep.var.labels = c("Cumulative founding in 1981 (logged)"),
          keep.stat = c("rsq", "n", "adj.rsq"),
          column.labels = c("Model 1",
                            "Model 2",
                            "Model 3",
                            "Model 4"),
          model.numbers = FALSE, 
          single.row = TRUE)

# Word output 
stargazer(m1, m2, m3, lm_white,
          title = "Cross-sectional regression analysis results",
          covariate.labels = c("OEO grants",
                                "Latino org",
                                "Asian pop",
                                "Latino pop",
                                "Poverty rate"),
          dep.var.labels = c("Cumulative founding in 1981 (logged)"),
          keep.stat = c("rsq", "n", "adj.rsq"),
          column.labels = c("Model 1",
                            "Model 2",
                            "Model 3",
                            "Model 4"),
          model.numbers = FALSE, 
          single.row = TRUE,
          type = "html",
          out = here("outputs", "cs_reg_analysis.doc"))
```

